### ISSUE TITLE
Vicious submodule moved so git submodule functions fail

### ISSUE THREAD

**Issue by RanceH** [tony/awesome-config#12]
https://git.sysphere.org/vicious/ moved to https://github.com/vicious-widgets/vicious

**Comment by tony** [comment]
@RanceH Thank you! Would you like to make a PR to update the submodule? (contributions welcome!)

**Comment by RanceH** [comment]
Surely

**Comment by RanceH** [comment]
PR created

**Comment by tony** [comment]
@RanceH Fixed via #13  / f454a5a

Better now?

**Comment by RanceH** [comment]
Looks like it.

**Comment by tony** [comment]
@RanceH Good, thank you!  Reach out if there's anything else that comes up. Will close this out for now
